# Generated by Django 5.0 on 2023-12-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uplaod', '0006_uploadedimage_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=100),
        ),
    ]
