# Generated by Django 5.0 on 2023-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uplaod', '0007_alter_uploadedimage_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=255, null=True),
        ),
    ]
